### ISSUE TITLE
Capcha

### ISSUE THREAD

**Issue by foshechka** [Porco-Rosso/vkdl#10]
http://inquty.podcastbox.ru
Look, just 10 entered the captcha and more can not.

**Comment by Porco-Rosso** [comment]
Open the app.js file, and you will find instructions to obtain your own api key. I'll copy it below:

---
- To get your own token you need first create vk application at https://vk.com/editapp?act=create
- Then  get your APP_ID and CLIENT_SECRET at application settings
- Now open this url from your (logged to vk) browser, this will redirect to blank.html with your token in the url:
- https://oauth.vk.com/authorize?client_id=APP_ID&client_secret=CLIENT_SECRET&scope=audio,offline&response_type=token
- Once you obtain the token from the url of the page that will load, replace it below, where it says: "accessToken: "
  
  ---
  
  ```
    //Config for vk audio.search api
    var vkConfig = {
        url: "https://api.vk.com/method/audio.search",
        sort: 2,
        autoComplete: 0,
        accessToken: "ccd09c5c990069316002d28ab7f0e0ba5841fbcdc626c0524afbe4faea92451ea43a4240cab3de8eda4df", // Public Vkdl 1
        count: 300
    };'
  ```

---

Getting a new api should fix a lot of the errors you have been receiving. Let me know if you have any trouble.

**Comment by foshechka** [comment]
Yes, I know that. I am wondering why you can not enter the captcha again.

**Comment by Porco-Rosso** [comment]
They block captcha attempts in order to stop bots from brute-forcing their way through the captchas by trial and error.
