### ISSUE TITLE
Oops, something went wrong : Flood control: too much captcha requests

### ISSUE THREAD

**Issue by foshechka** [Porco-Rosso/vkdl#4]
No shows captcha!

**Comment by Porco-Rosso** [comment]
The Api token limit was reached, I have changed it now.

Let me know if this problem still appears.

**Comment by foshechka** [comment]
Ok, thnks.

**Comment by foshechka** [comment]
Oops, something went wrong : Flood control: too much captcha requests - all the same mistake, but the window does not show a CAPTCHA.((

**Comment by Porco-Rosso** [comment]
What internet browser are you using? Have you completed the captcha before? Are you loading the page from this link: https://rawgit.com/Porco-Rosso/vkdl/master/index.html ?

**Comment by foshechka** [comment]
FireFox. In all browsers. CAPTCHA is displayed several times, and then the error, but there is no captcha.

**Comment by Porco-Rosso** [comment]
Are you sure you are typing in the captchas correctly when the prompt appears? they can be tricky at times.
Also wait a few moments, sometimes it takes a little while before the captcha image loads inside the prompt.

**Comment by Porco-Rosso** [comment]
I'm assuming this issue was resolved? closing.
