### ISSUE TITLE
Song length

### ISSUE THREAD

**Issue by foshechka** [Porco-Rosso/vkdl#8]
Please fix it. If found, for example, a podcast that is longer than 59 minutes, then after 60 minutes shows the length of the song 00: ...

**Comment by Porco-Rosso** [comment]
could you write the name of the podcast that you are trying to download? so I can reproduce the bug?

**Comment by foshechka** [comment]
Any audio file that is greater than 59 minutes.
Danny Avila – 123 – Ready To Jump  (1:02:52)

**Comment by foshechka** [comment]
Danny Avila – 123 – Ready To Jump

**Comment by Porco-Rosso** [comment]
should be working fine now :+1:
